<?php
@session_start();
if(!empty($_SESSION['user'])){
    unset($_SESSION['user']);
}
if(!empty($_SESSION['name'])){
    unset($_SESSION['name']);
}
if(!empty($_SESSION['role'])){
    unset($_SESSION['role']);
}
if(!empty($_SESSION['userid'])){
    unset($_SESSION['userid']);
}
session_regenerate_id(1);
session_destroy();
header("Location: ./");
exit();
?>